import { type Module, inject } from "langium";
import {
  createDefaultModule,
  createDefaultSharedModule,
  type DefaultSharedModuleContext,
  type LangiumServices,
  type LangiumSharedServices,
  type PartialLangiumServices,
} from "langium/lsp";
import {
  RexxGeneratedModule,
  RexxGeneratedSharedModule,
} from "./generated/module.js";
import { RexxValidator, registerValidationChecks } from "./rexx-validator.js";
import { RexxSemanticTokenProvider } from "./rexx-semantic-token-provider.js";

/**
 * Declaration of custom services - add your own service classes here.
 */
export type RexxAddedServices = {
  validation: {
    RexxValidator: RexxValidator;
  };
};

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type RexxServices = LangiumServices & RexxAddedServices;

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const RexxModule: Module<
  RexxServices,
  PartialLangiumServices & RexxAddedServices
> = {
  validation: {
    RexxValidator: () => new RexxValidator(),
  },
  lsp: {
    SemanticTokenProvider: (services) =>
      new RexxSemanticTokenProvider(services),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createRexxServices(context: DefaultSharedModuleContext): {
  shared: LangiumSharedServices;
  Rexx: RexxServices;
} {
  const shared = inject(
    createDefaultSharedModule(context),
    RexxGeneratedSharedModule
  );
  const Rexx = inject(
    createDefaultModule({ shared }),
    RexxGeneratedModule,
    RexxModule
  );
  shared.ServiceRegistry.register(Rexx);
  registerValidationChecks(Rexx);
  if (!context.connection) {
    // We don't run inside a language server
    // Therefore, initialize the configuration provider instantly
    shared.workspace.ConfigurationProvider.initialized({});
  }
  return { shared, Rexx };
}
